server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  
 
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
        
        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loans/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
